version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/auth-app
      - JWT_SECRET=secret
    depends_on:
      - mongo

  frontend:
    build:
      context: ./mern-auth-frontend
    container_name: frontend
    ports:
      - "3002:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    depends_on:
      - backend

volumes:
  mongo-data:
