version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: rajansahni/college-backend
    container_name: college-backend-container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/auth-app
      - JWT_SECRET=secret
    depends_on:
      - mongo
    volumes:
      - /app/backend/data:/usr/src/app/data

  frontend:
    image: rajansahni/college-frontend
    container_name: college-frontend-container
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - /app/frontend/build:/usr/share/nginx/html

volumes:
  mongo-data:
